// flow-typed signature: 3ea26ed5701b307fd73b005b70ba1576
// flow-typed version: <<STUB>>/react-native-axios_v^0.17.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-axios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-axios/dist/axios' {
  declare module.exports: any;
}

declare module 'react-native-axios/dist/axios.min' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/adapters/fetch' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/adapters/http' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/adapters/xhr' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/axios' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/core/Axios' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/core/createError' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/core/dispatchRequest' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/core/enhanceError' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/core/InterceptorManager' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/core/settle' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/core/transformData' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/defaults' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/bind' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/btoa' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/buildURL' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/combineURLs' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/cookies' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/deprecatedMethod' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/isAbsoluteURL' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/isURLSameOrigin' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/normalizeHeaderName' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/parseHeaders' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/helpers/spread' {
  declare module.exports: any;
}

declare module 'react-native-axios/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-axios/dist/axios.js' {
  declare module.exports: $Exports<'react-native-axios/dist/axios'>;
}
declare module 'react-native-axios/dist/axios.min.js' {
  declare module.exports: $Exports<'react-native-axios/dist/axios.min'>;
}
declare module 'react-native-axios/index' {
  declare module.exports: $Exports<'react-native-axios'>;
}
declare module 'react-native-axios/index.js' {
  declare module.exports: $Exports<'react-native-axios'>;
}
declare module 'react-native-axios/lib/adapters/fetch.js' {
  declare module.exports: $Exports<'react-native-axios/lib/adapters/fetch'>;
}
declare module 'react-native-axios/lib/adapters/http.js' {
  declare module.exports: $Exports<'react-native-axios/lib/adapters/http'>;
}
declare module 'react-native-axios/lib/adapters/xhr.js' {
  declare module.exports: $Exports<'react-native-axios/lib/adapters/xhr'>;
}
declare module 'react-native-axios/lib/axios.js' {
  declare module.exports: $Exports<'react-native-axios/lib/axios'>;
}
declare module 'react-native-axios/lib/core/Axios.js' {
  declare module.exports: $Exports<'react-native-axios/lib/core/Axios'>;
}
declare module 'react-native-axios/lib/core/createError.js' {
  declare module.exports: $Exports<'react-native-axios/lib/core/createError'>;
}
declare module 'react-native-axios/lib/core/dispatchRequest.js' {
  declare module.exports: $Exports<'react-native-axios/lib/core/dispatchRequest'>;
}
declare module 'react-native-axios/lib/core/enhanceError.js' {
  declare module.exports: $Exports<'react-native-axios/lib/core/enhanceError'>;
}
declare module 'react-native-axios/lib/core/InterceptorManager.js' {
  declare module.exports: $Exports<'react-native-axios/lib/core/InterceptorManager'>;
}
declare module 'react-native-axios/lib/core/settle.js' {
  declare module.exports: $Exports<'react-native-axios/lib/core/settle'>;
}
declare module 'react-native-axios/lib/core/transformData.js' {
  declare module.exports: $Exports<'react-native-axios/lib/core/transformData'>;
}
declare module 'react-native-axios/lib/defaults.js' {
  declare module.exports: $Exports<'react-native-axios/lib/defaults'>;
}
declare module 'react-native-axios/lib/helpers/bind.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/bind'>;
}
declare module 'react-native-axios/lib/helpers/btoa.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/btoa'>;
}
declare module 'react-native-axios/lib/helpers/buildURL.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/buildURL'>;
}
declare module 'react-native-axios/lib/helpers/combineURLs.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/combineURLs'>;
}
declare module 'react-native-axios/lib/helpers/cookies.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/cookies'>;
}
declare module 'react-native-axios/lib/helpers/deprecatedMethod.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/deprecatedMethod'>;
}
declare module 'react-native-axios/lib/helpers/isAbsoluteURL.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/isAbsoluteURL'>;
}
declare module 'react-native-axios/lib/helpers/isURLSameOrigin.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/isURLSameOrigin'>;
}
declare module 'react-native-axios/lib/helpers/normalizeHeaderName.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/normalizeHeaderName'>;
}
declare module 'react-native-axios/lib/helpers/parseHeaders.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/parseHeaders'>;
}
declare module 'react-native-axios/lib/helpers/spread.js' {
  declare module.exports: $Exports<'react-native-axios/lib/helpers/spread'>;
}
declare module 'react-native-axios/lib/utils.js' {
  declare module.exports: $Exports<'react-native-axios/lib/utils'>;
}
